"""
train_logistic.py
-----------------
Logistic Regression training, hyperparameter tuning, evaluation, and model saving.
Responsible: Berat Celik (bc729)

Usage:
    python train_logistic.py

Expects preprocessed .npy files in saved_models/ (generated by preprocessing.py).
"""

import numpy as np
import os
import time

from evaluation import (
    compute_all_metrics,
    print_metrics,
    confusion_matrix,
    roc_curve_data,
)

# ─────────────────────────────────────────────
# 1. LOGISTIC REGRESSION CLASSIFIER
# ─────────────────────────────────────────────


class LogisticRegression:
    """
    Logistic Regression classifier implemented from scratch with NumPy.

    Parameters
    ----------
    lr : float
        Learning rate for gradient descent.
    n_iters : int
        Number of gradient descent iterations.
    """

    def __init__(self, lr: float = 0.01, n_iters: int = 5000):
        self.lr = lr
        self.n_iters = n_iters
        self.w = None
        self.b = None

    def sigmoid(self, z: np.ndarray) -> np.ndarray:
        z = np.clip(z, -500, 500)
        return 1 / (1 + np.exp(-z))

    def fit(self, X: np.ndarray, y: np.ndarray) -> "LogisticRegression":
        """
        Train the model using gradient descent on binary cross-entropy loss.
        """
        n_samples, n_features = X.shape
        self.w = np.zeros(n_features)
        self.b = 0.0

        for _ in range(self.n_iters):
            linear = np.dot(X, self.w) + self.b
            y_pred = self.sigmoid(linear)

            dw = (1 / n_samples) * np.dot(X.T, (y_pred - y))
            db = (1 / n_samples) * np.sum(y_pred - y)

            self.w -= self.lr * dw
            self.b -= self.lr * db

        return self

    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """Return P(fraud) for each sample."""
        linear = np.dot(X, self.w) + self.b
        return self.sigmoid(linear)

    def predict(self, X: np.ndarray, threshold: float = 0.5) -> np.ndarray:
        """Return binary predictions using the given threshold."""
        probs = self.predict_proba(X)
        return (probs >= threshold).astype(int)

    # ── Model Persistence ─────────────────────

    def save(self, save_dir: str = "saved_models", threshold: float = 0.5) -> None:
        """Save model weights, bias, and best threshold to disk."""
        os.makedirs(save_dir, exist_ok=True)
        np.save(os.path.join(save_dir, "logreg_weights.npy"), self.w)
        np.save(os.path.join(save_dir, "logreg_bias.npy"), np.array([self.b]))
        np.save(os.path.join(save_dir, "logreg_threshold.npy"), np.array([threshold]))
        print(f"  LR model saved to {save_dir}/")

    @classmethod
    def load(cls, save_dir: str = "saved_models") -> tuple:
        """
        Load a saved LR model from disk.

        Returns
        -------
        model : LogisticRegression (with weights loaded)
        threshold : float
        """
        model = cls()
        model.w = np.load(os.path.join(save_dir, "logreg_weights.npy"))
        model.b = float(np.load(os.path.join(save_dir, "logreg_bias.npy"))[0])
        threshold = float(np.load(os.path.join(save_dir, "logreg_threshold.npy"))[0])
        print(f"  LR model loaded from {save_dir}/ (threshold={threshold})")
        return model, threshold


# ─────────────────────────────────────────────
# 2. MAIN TRAINING PIPELINE
# ─────────────────────────────────────────────


def main():
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    SAVE_DIR = os.path.join(BASE_DIR, "saved_models")

    # ─── 1. Load preprocessed data ───────────────
    print("\n" + "=" * 60)
    print("  Logistic Regression Training Pipeline")
    print("=" * 60)

    print("\n>>> Step 1: Loading preprocessed data")
    X_train = np.load(os.path.join(SAVE_DIR, "X_train.npy"))
    y_train = np.load(os.path.join(SAVE_DIR, "y_train.npy"))
    X_test = np.load(os.path.join(SAVE_DIR, "X_test.npy"))
    y_test = np.load(os.path.join(SAVE_DIR, "y_test.npy"))

    print(
        f"  X_train: {X_train.shape}  (fraud={np.sum(y_train==1)}, legit={np.sum(y_train==0)})"
    )
    print(
        f"  X_test:  {X_test.shape}  (fraud={np.sum(y_test==1)}, legit={np.sum(y_test==0)})"
    )

    # ─── 2. Hyperparameter tuning ────────────────
    print("\n>>> Step 2: Hyperparameter tuning (grid search)")

    learning_rates = [0.001, 0.01, 0.1]
    iteration_options = [1000, 5000, 10000]
    thresholds = [0.3, 0.4, 0.5]

    total_configs = len(learning_rates) * len(iteration_options) * len(thresholds)
    config_num = 0

    print(f"  Learning rates: {learning_rates}")
    print(f"  Iterations:     {iteration_options}")
    print(f"  Thresholds:     {thresholds}")
    print(f"  Total configs:  {total_configs}")

    best_model = None
    best_probs = None
    best_result = None
    best_threshold = None
    best_lr = None
    best_iters = None

    t0 = time.time()

    for lr in learning_rates:
        for n_iters in iteration_options:
            temp_model = LogisticRegression(lr=lr, n_iters=n_iters)
            temp_model.fit(X_train, y_train)
            probs = temp_model.predict_proba(X_test)

            for threshold in thresholds:
                config_num += 1
                y_pred = (probs >= threshold).astype(int)
                metrics = compute_all_metrics(y_test, y_pred, probs)

                print(
                    f"  [{config_num:2d}/{total_configs}]  "
                    f"lr={lr}  iters={n_iters:5d}  thresh={threshold}  "
                    f"f1={metrics['f1']:.4f}  recall={metrics['recall']:.4f}"
                )

                # Pick best by F1, break ties by recall
                if (
                    best_result is None
                    or metrics["f1"] > best_result["f1"]
                    or (
                        metrics["f1"] == best_result["f1"]
                        and metrics["recall"] > best_result["recall"]
                    )
                ):
                    best_result = metrics
                    best_model = temp_model
                    best_probs = probs
                    best_threshold = threshold
                    best_lr = lr
                    best_iters = n_iters

    tuning_time = time.time() - t0
    print(f"\n  Tuning completed in {tuning_time:.1f} seconds.")
    print(f"  >>> Best: lr={best_lr}, iters={best_iters}, threshold={best_threshold}")

    # ─── 3. Evaluate on training set ─────────────
    print("\n>>> Step 3: Evaluating on training set")
    y_train_proba = best_model.predict_proba(X_train)
    y_train_pred = (y_train_proba >= best_threshold).astype(int)

    train_metrics = compute_all_metrics(y_train, y_train_pred, y_train_proba)
    print_metrics(train_metrics, header="Training Set Metrics")

    cm_train = confusion_matrix(y_train, y_train_pred)
    print("\n  Training Confusion Matrix:")
    print(f"    TN={cm_train[0,0]:5d}  FP={cm_train[0,1]:5d}")
    print(f"    FN={cm_train[1,0]:5d}  TP={cm_train[1,1]:5d}")

    # ─── 4. Evaluate on test set ─────────────────
    print("\n>>> Step 4: Evaluating on test set (original class distribution)")
    y_test_pred = (best_probs >= best_threshold).astype(int)
    test_metrics = best_result

    print_metrics(test_metrics, header="Test Set Metrics")

    cm_test = confusion_matrix(y_test, y_test_pred)
    print("\n  Test Confusion Matrix:")
    print(f"    TN={cm_test[0,0]:5d}  FP={cm_test[0,1]:5d}")
    print(f"    FN={cm_test[1,0]:5d}  TP={cm_test[1,1]:5d}")

    # ─── 5. Overfitting check ────────────────────
    print("\n>>> Step 5: Overfitting Analysis")
    print(f"  {'Metric':12s}  {'Train':>8s}  {'Test':>8s}  {'Gap':>8s}")
    print(f"  {'-'*40}")
    for metric_name in ["precision", "recall", "f1", "auc_roc"]:
        tr = train_metrics[metric_name]
        te = test_metrics[metric_name]
        gap = tr - te
        flag = " !!" if abs(gap) > 0.10 else ""
        print(f"  {metric_name:12s}  {tr:8.4f}  {te:8.4f}  {gap:+8.4f}{flag}")

    # ─── 6. Save model and artifacts ─────────────
    print("\n>>> Step 6: Saving model and artifacts")
    best_model.save(save_dir=SAVE_DIR, threshold=best_threshold)

    # Save test predictions and probabilities
    np.save(os.path.join(SAVE_DIR, "logreg_test_pred.npy"), y_test_pred)
    np.save(os.path.join(SAVE_DIR, "logreg_test_proba.npy"), best_probs)

    # Save ROC curve data for Streamlit
    fpr, tpr, thresholds_roc = roc_curve_data(y_test, best_probs)
    np.save(os.path.join(SAVE_DIR, "logreg_roc_fpr.npy"), fpr)
    np.save(os.path.join(SAVE_DIR, "logreg_roc_tpr.npy"), tpr)

    # Save tuning summary
    tuning_summary = {
        "best_lr": best_lr,
        "best_iters": best_iters,
        "best_threshold": best_threshold,
        "test_metrics": test_metrics,
        "train_metrics": train_metrics,
        "confusion_matrix_test": cm_test,
    }
    np.save(
        os.path.join(SAVE_DIR, "logreg_tuning_summary.npy"),
        tuning_summary,
        allow_pickle=True,
    )

    # Also save human-readable results
    with open(os.path.join(SAVE_DIR, "logreg_results.txt"), "w") as f:
        f.write(f"Best LR: {best_lr}\n")
        f.write(f"Iterations: {best_iters}\n")
        f.write(f"Threshold: {best_threshold}\n")
        f.write(f"Precision: {test_metrics['precision']}\n")
        f.write(f"Recall: {test_metrics['recall']}\n")
        f.write(f"F1: {test_metrics['f1']}\n")
        f.write(f"AUC: {test_metrics['auc_roc']}\n")

    print(f"\n  All artifacts saved to {SAVE_DIR}/:")
    print("    logreg_weights.npy         - model weights")
    print("    logreg_bias.npy            - model bias")
    print("    logreg_threshold.npy       - best threshold")
    print("    logreg_test_pred.npy       - test predictions")
    print("    logreg_test_proba.npy      - test probabilities")
    print("    logreg_roc_fpr/tpr.npy     - ROC curve data")
    print("    logreg_tuning_summary.npy  - full results summary")
    print("    logreg_results.txt         - human-readable summary")

    print(f"\n{'=' * 60}")
    print("  Logistic Regression Pipeline Complete!")
    print(f"  Best model: lr={best_lr}, iters={best_iters}, threshold={best_threshold}")
    print(
        f"  Test F1={test_metrics['f1']:.4f}  "
        f"Recall={test_metrics['recall']:.4f}  "
        f"AUC-ROC={test_metrics['auc_roc']:.4f}"
    )
    print(f"{'=' * 60}\n")


if __name__ == "__main__":
    main()
