"""
train_knn.py
------------
End-to-end KNN training, hyperparameter tuning, evaluation, and model saving.
Responsible: Yuxiang Jiang (yj548)

Usage:
    python train_knn.py

Expects preprocessed .npy files in saved_models/ (generated by preprocessing.py).
"""

import numpy as np
import os
import time

from knn import KNNClassifier, tune_hyperparameters
from evaluation import (
    compute_all_metrics,
    print_metrics,
    confusion_matrix,
    roc_curve_data,
)


def main():
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    SAVE_DIR = os.path.join(BASE_DIR, "saved_models")

    # ─── 1. Load preprocessed data ───────────────
    print("\n" + "=" * 60)
    print("  KNN Training Pipeline")
    print("=" * 60)

    print("\n>>> Step 1: Loading preprocessed data")
    X_train = np.load(os.path.join(SAVE_DIR, "X_train.npy"))
    y_train = np.load(os.path.join(SAVE_DIR, "y_train.npy"))
    X_test = np.load(os.path.join(SAVE_DIR, "X_test.npy"))
    y_test = np.load(os.path.join(SAVE_DIR, "y_test.npy"))

    print(
        f"  X_train: {X_train.shape}  (fraud={np.sum(y_train==1)}, legit={np.sum(y_train==0)})"
    )
    print(
        f"  X_test:  {X_test.shape}  (fraud={np.sum(y_test==1)}, legit={np.sum(y_test==0)})"
    )

    # ─── 2. Hyperparameter tuning via 5-fold CV ──
    print("\n>>> Step 2: Hyperparameter tuning (5-fold stratified CV)")
    t0 = time.time()

    tuning_results = tune_hyperparameters(
        X_train,
        y_train,
        k_values=[3, 5, 7, 11, 15],
        weight_options=["uniform", "distance"],
        n_folds=5,
        scoring="f1",  # optimize for F1 (balances precision & recall)
        random_state=42,
        verbose=True,
    )

    tuning_time = time.time() - t0
    print(f"  Tuning completed in {tuning_time:.1f} seconds.")

    best_k = tuning_results["best_k"]
    best_weights = tuning_results["best_weights"]

    # ─── 3. Train final model with best hyperparameters ──
    print(f"\n>>> Step 3: Training final model (k={best_k}, weights={best_weights})")
    model = KNNClassifier(k=best_k, weights=best_weights)
    model.fit(X_train, y_train)

    # ─── 4. Evaluate on training set ─────────────
    print("\n>>> Step 4: Evaluating on training set")
    t0 = time.time()
    y_train_pred = model.predict(X_train)
    y_train_proba = model.predict_proba(X_train)[:, 1]
    train_time = time.time() - t0

    train_metrics = compute_all_metrics(y_train, y_train_pred, y_train_proba)
    print_metrics(train_metrics, header="Training Set Metrics")

    cm_train = confusion_matrix(y_train, y_train_pred)
    print("\n  Training Confusion Matrix:")
    print(f"    TN={cm_train[0,0]:5d}  FP={cm_train[0,1]:5d}")
    print(f"    FN={cm_train[1,0]:5d}  TP={cm_train[1,1]:5d}")
    print(f"  Training prediction time: {train_time:.2f}s")

    # ─── 5. Evaluate on test set ─────────────────
    print("\n>>> Step 5: Evaluating on test set (original class distribution)")
    t0 = time.time()
    y_test_pred = model.predict(X_test)
    y_test_proba = model.predict_proba(X_test)[:, 1]
    test_time = time.time() - t0

    test_metrics = compute_all_metrics(y_test, y_test_pred, y_test_proba)
    print_metrics(test_metrics, header="Test Set Metrics")

    cm_test = confusion_matrix(y_test, y_test_pred)
    print("\n  Test Confusion Matrix:")
    print(f"    TN={cm_test[0,0]:5d}  FP={cm_test[0,1]:5d}")
    print(f"    FN={cm_test[1,0]:5d}  TP={cm_test[1,1]:5d}")
    print(f"  Test prediction time: {test_time:.2f}s " f"({X_test.shape[0]} samples)")

    # ─── 6. Overfitting check ────────────────────
    print("\n>>> Step 6: Overfitting Analysis")
    print(f"  {'Metric':12s}  {'Train':>8s}  {'Test':>8s}  {'Gap':>8s}")
    print(f"  {'-'*40}")
    for metric_name in ["precision", "recall", "f1", "auc_roc"]:
        tr = train_metrics[metric_name]
        te = test_metrics[metric_name]
        gap = tr - te
        flag = " ⚠" if abs(gap) > 0.10 else ""
        print(f"  {metric_name:12s}  {tr:8.4f}  {te:8.4f}  {gap:+8.4f}{flag}")

    # ─── 7. Save model ───────────────────────────
    print("\n>>> Step 7: Saving model")
    model.save(save_dir=SAVE_DIR)

    # Also save test predictions and ROC data for Streamlit visualization
    np.save(os.path.join(SAVE_DIR, "knn_test_pred.npy"), y_test_pred)
    np.save(os.path.join(SAVE_DIR, "knn_test_proba.npy"), y_test_proba)

    fpr, tpr, thresholds = roc_curve_data(y_test, y_test_proba)
    np.save(os.path.join(SAVE_DIR, "knn_roc_fpr.npy"), fpr)
    np.save(os.path.join(SAVE_DIR, "knn_roc_tpr.npy"), tpr)

    # Save tuning results summary
    tuning_summary = {
        "best_k": best_k,
        "best_weights": best_weights,
        "best_cv_score": tuning_results["best_score"],
        "test_metrics": test_metrics,
        "train_metrics": train_metrics,
        "confusion_matrix_test": cm_test,
    }
    np.save(
        os.path.join(SAVE_DIR, "knn_tuning_summary.npy"),
        tuning_summary,
        allow_pickle=True,
    )

    print(f"\n  All artifacts saved to {SAVE_DIR}/:")
    print("    knn_X_train.npy        — stored training data (for prediction)")
    print("    knn_y_train.npy        — stored training labels")
    print("    knn_params.npy         — hyperparameters (k, weights)")
    print("    knn_test_pred.npy      — test predictions")
    print("    knn_test_proba.npy     — test probabilities")
    print("    knn_roc_fpr/tpr.npy    — ROC curve data")
    print("    knn_tuning_summary.npy — full results summary")

    print(f"\n{'=' * 60}")
    print("  KNN Pipeline Complete!")
    print(f"  Best model: k={best_k}, weights={best_weights}")
    print(
        f"  Test F1={test_metrics['f1']:.4f}  "
        f"Recall={test_metrics['recall']:.4f}  "
        f"AUC-ROC={test_metrics['auc_roc']:.4f}"
    )
    print(f"{'=' * 60}\n")


if __name__ == "__main__":
    main()
